<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-hover table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>
                    Месяц
                </th>
                <th>
                    Баланс
                </th>
            </tr>
            </thead>
            <tbody>
            <? foreach($this->balance as $row):?>
                <tr>
                    <td>
                        <?= strftime('%m/%Y', strtotime($row['date']))?>
                    </td>
                    <td>
                        <?= $row['total'] ?>
                    </td>
                </tr>
            <?endforeach;?>
            </tbody>
        </table>
    </div>
</div>
