<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-hover table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>
                    <?= $this->avg[2]['name'] ?>
                </th>
                <th>
                    <?= $this->avg[1]['name'] ?>
                </th>
                <th>
                    <?= $this->avg[0]['name'] ?>
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <?= $this->avg[2]['sum_avg'] ? round($this->avg[2]['sum_avg']) : 0 ?>
                </td>
                <td>
                    <?= $this->avg[1]['sum_avg'] ? round($this->avg[1]['sum_avg']) : 0 ?>
                </td>
                <td>
                    <?= $this->avg[0]['sum_avg'] ? round($this->avg[0]['sum_avg']) : 0 ?>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
