<div class="row">
    <div class="col-xs-12">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <blockquote class="card-blockquote">
                    <h2>Описание cron</h2>
                    <p>
                        Процесс начисления процентов сработает если перейти <a class="text-info" href="http://bank/calculate/percent" target="_blank">по этой ссылке</a>
                    </p>
                    <p>
                        Процесс списания комиссии сработает если перейти <a class="text-info" href="http://bank/calculate/commission" target="_blank">по этой ссылке</a>
                    </p>
                    <p>
                        По идеие cron начисления процентов отрабатывает каждый день, а по списанию комиссии каждое 1-е число на несколько часов позже первого cron`a
                    </p>
                </blockquote>
            </div>
        </div>
    </div>
</div>